apiVersion: v1
kind: Service
metadata:
  name: clod2aip-service

spec:
  selector:
    app: regapp          # should match with deployment label

  ports:
    - port: 8080         #LB Port
      targetPort: 8080   #Container Port


  type: LoadBalancer
