apiVersion: apps/v1
kind: Deployment
metadata:
  name: clod2aip-regapp
  labels:
     app: regapp          # should match with service selector

spec:
  replicas: 3
  selector:
    matchLabels:
      app: regapp
  template:
    metadata:
      labels:
        app: regapp
    spec:
      containers:
      - name: regapp
        image: krishnasai98/regapp
        imagePullPolicy: Always # Always pull latest image
        ports:
        - containerPort: 8080    # Container Port

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
# Strategy section is all about make sure update only one pod at a time
